FROM python:3.10-slim

# Install required build tools
RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    python3-dev \
    python3-distutils \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY api/app.py ./
COPY api/requirements.txt ./
COPY api/qos_xgb_model.pkl ./

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

CMD ["python", "app.py"]
